version: "3.8"
services: 
  
  virtuoso: 
    image: tenforce/virtuoso
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      - DBA_PASSWORD=${DBA_PASSWORD}
        #- SPARQL_UPDATE=${SPARQL_UPDATE}
      - DEFAULT_GRAPH=${DEFAULT_GRAPH}


        #  lodview:
        #    build: ./LodView
        #    restart: unless-stopped
        #    ports:
        #      - "8889:8080"
        #    depends_on: 
        #      - virtuoso
